export const ACTION_LOADING_START = 'LOADING_START';
export const ACTION_LOADING_END = 'LOADING_END';

export const SET_BOTTOM_MODAL = 'SET_BOTTOM_MODAL';

export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';

export const SET_PLACES_LIST = 'SET_PLACES_LIST';
export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE';
